use_frameworks!

target 'WebViewRTCDataChannel_Example' do
  pod 'WebViewRTCDataChannel', :path => '../'

  target 'WebViewRTCDataChannel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
